name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install poetry
        run: |
          poetry install
      - name: Show poetry debug information
        run: |
          poetry debug
      - name: Check syntax
        run: |
          poetry run black --check .
      - name: Run tests
        run: |
          poetry run pytest tests/ --junitxml=junit/test-results.xml --cov=symnet_cp --cov-report=xml --cov-report=html
