name: Tests

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ "3.11", "3.12" ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install poetry
        run: |
          poetry install
      - name: Show poetry debug information
        run: |
          poetry debug info
      - name: Check formatting
        run: |
          poetry run black --diff --check .
          poetry run isort --check .
      - name: Check style guide
        run: |
          poetry run flake8
      - name: Run tests
        run: |
          poetry run pytest tests -p no:sugar --cov=symnet_cp --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.11'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
